# Generated by Django 4.2.2 on 2025-02-25 23:21

import apps.authenticacion.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=45, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('password', models.CharField(max_length=100)),
                ('resetToken', models.CharField(blank=True, max_length=256, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.authenticacion.models.path_to_avatar)),
                ('codigo', models.CharField(default='SIN_CODIGO', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='categoriaTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updateAt', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría de Tipo',
                'verbose_name_plural': 'Categorías de Tipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updateAt', models.DateField(auto_now=True)),
                ('path', models.CharField(max_length=256)),
                ('id_padre', models.IntegerField()),
                ('method', models.CharField(max_length=256)),
                ('icono', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=256)),
                ('titulo', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Resources',
                'verbose_name_plural': 'Resources',
            },
        ),
        migrations.CreateModel(
            name='ResourceRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updateAt', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='authenticacion.resource')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updateAt', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('resources', models.ManyToManyField(related_name='roles_resource', through='authenticacion.ResourceRol', to='authenticacion.resource')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='UserRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('rolesId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_users', to='authenticacion.rol')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User_rols',
                'verbose_name_plural': 'user_rols',
                'unique_together': {('userId', 'rolesId')},
            },
        ),
        migrations.CreateModel(
            name='tablaMaestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updateAt', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='authenticacion.categoriatipo')),
            ],
            options={
                'verbose_name': 'Tabla Tipo',
                'verbose_name_plural': 'Tablas Tipo',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='rol',
            name='users',
            field=models.ManyToManyField(related_name='roles_rol', through='authenticacion.UserRol', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcerol',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources_rols', to='authenticacion.rol'),
        ),
        migrations.AddField(
            model_name='resource',
            name='roles',
            field=models.ManyToManyField(related_name='resources_rol', through='authenticacion.ResourceRol', to='authenticacion.rol'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updateAt', models.DateField(auto_now=True)),
                ('identificacion', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.BigIntegerField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('barrio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barrio', to='authenticacion.tablamaestra')),
                ('ciudad_nacimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciudad_nacimiento', to='authenticacion.tablamaestra')),
                ('ciudad_residencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciudad_residencia', to='authenticacion.tablamaestra')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamento', to='authenticacion.tablamaestra')),
                ('document_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='authenticacion.tablamaestra')),
                ('estado_civil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estados_civiles', to='authenticacion.tablamaestra')),
                ('estrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estrato', to='authenticacion.tablamaestra')),
                ('genero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genero', to='authenticacion.tablamaestra')),
                ('grupoEtnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_etnicos', to='authenticacion.tablamaestra')),
                ('nivelFormacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='niveles_formacion', to='authenticacion.tablamaestra')),
                ('situacion_laboral', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='situacion_laboral', to='authenticacion.tablamaestra')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updateAt', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('Fecha', models.DateField(auto_now_add=True)),
                ('talla', models.FloatField()),
                ('peso', models.FloatField()),
                ('perimetro_cintura', models.FloatField(null=True)),
                ('perimetro_cadera', models.FloatField(null=True)),
                ('pliegue_pectoral', models.FloatField(blank=True, null=True)),
                ('pliegue_abdominal', models.FloatField(blank=True, null=True)),
                ('pliegue_antemuslo', models.FloatField(blank=True, null=True)),
                ('pliegue_tricipal', models.FloatField(blank=True, null=True)),
                ('pliegue_iliocrestal', models.FloatField(blank=True, null=True)),
                ('fuerza_manoderecha', models.FloatField(null=True)),
                ('fuerza_manoizquierda', models.FloatField(null=True)),
                ('equilibrio', models.FloatField(blank=True, null=True)),
                ('resistencia_abdominal', models.FloatField(blank=True, null=True)),
                ('fuerza_explosiva_i', models.FloatField(blank=True, null=True)),
                ('fuerza_explosiva_f', models.FloatField(blank=True, null=True)),
                ('resistencia_cardiorespiratoria', models.FloatField(blank=True, null=True)),
                ('tiempo_resistencia_cardiorespiratoria', models.FloatField(blank=True, null=True)),
                ('frecuencia_cardiaca', models.FloatField(blank=True, null=True)),
                ('volumen_max_oxigeno', models.FloatField(blank=True, null=True)),
                ('flexibilidad', models.FloatField(blank=True, null=True)),
                ('caff', models.FloatField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.ManyToManyField(related_name='users_customuser', through='authenticacion.UserRol', to='authenticacion.rol'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddConstraint(
            model_name='resourcerol',
            constraint=models.UniqueConstraint(fields=('resource', 'role'), name='unique_resource_role'),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('user', 'identificacion')},
        ),
    ]
