# Generated by Django 4.2.2 on 2025-03-04 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updateAt', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('duracion_semanas', models.IntegerField()),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrenamientos_asignados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrenamientos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrenamiento',
                'verbose_name_plural': 'Entrenamientos',
            },
        ),
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updateAt', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('calorias_diarias', models.IntegerField()),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentaciones_asignadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alimentación',
                'verbose_name_plural': 'Planes de Alimentación',
            },
        ),
    ]
